services:
  - type: web
    name: screenshot-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python screenshot_server.py
    plan: free
